-- +migration Up
CREATE TABLE live_alert_users (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "nick_name" TEXT NOT NULL,
  "email" TEXT NOT NULL UNIQUE,
  "password" TEXT NOT NULL,
  "safeword" TEXT NOT NULL
);

-- +migration Down
DROP TABLE IF EXISTS "live_alert_users";



-- CREATE TABLE live_alert_users (
--   id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--   nick_name TEXT NOT NULL,
--   email TEXT NOT NULL UNIQUE,
--   password TEXT NOT NULL,
--   safeword TEXT NOT NULL
-- );